name: Build and test LinkSiren

on: [push, pull_request]

jobs:
    lint:
        name: Lint and auto-fix with ruff
        runs-on: ubuntu-latest
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository

        steps:
            - name: Checkout LinkSiren
              uses: actions/checkout@v4

            - name: Set up Python
                uses: actions/setup-python@v5
                with:
                    python-version: '3.12'

            - name: Install Build and Test Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pytest coverage black ruff

            - name: Install LinkSiren dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt

            - name: Install the






    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
    with:
        python-version: '3.12'
        cache: 'pip'
    - name: Install dependencies
    run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
    run: |
        pip install pytest coverage
        python -m coverage run -m pytest
        python -m coverage html

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
    uses: actions/setup-python@v5
    with:
        python-version: '3.12'
    - name: Install the code linting and formatting tool Ruff
    run: pipx install ruff
    - name: Lint code with Ruff
    run: ruff check --output-format=github --target-version=py312
    continue-on-error: true